FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    qemu-user \
    qemu-user-static \
    gcc-mipsel-linux-gnu \
    gcc-mips64el-linux-gnuabi64 \
    wget \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src