FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    qemu-user \
    qemu-user-static \
    gcc-riscv64-linux-gnu \
    wget \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src