name: aarch64-alpine-linux

on: [push, pull_request]

jobs:
  setup-aarch64-alpine-linux:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.alpine-aarch64 .

  build-aarch64-alpine-linux:
    runs-on: ubuntu-latest-arm64
    needs: setup-aarch64-alpine-linux
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.alpine-aarch64 .
      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            sh -c "mkdir -p build && cd build && \
            cmake -DTARGET=aarch64-pc-linux-gnu \
                  -DCMAKE_C_COMPILER=gcc \
                  -DCMAKE_SYSTEM_NAME=Linux \
                  .. && \
            cmake --build ."
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-aarch64-alpine-linux
          path: build/

  test-aarch64-alpine-linux:
    runs-on: ubuntu-latest-arm64
    needs: build-aarch64-alpine-linux
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-aarch64-alpine-linux
          path: build/
      - name: Restore execute permissions
        run: chmod +x build/bin/*
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.alpine-aarch64 .
      - name: Run Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            sh -c "cd build && ctest --output-on-failure"
