name: aarch64-apple-darwin

on: [push, pull_request]

jobs:
    setup-aarch64-apple-darwin:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: brew install cmake

    build-aarch64-apple-darwin:
        runs-on: macos-15
        needs: setup-aarch64-apple-darwin
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: brew install cmake
            - name: Configure
              run: |
                  mkdir -p build && cd build
                  cmake -G "Unix Makefiles" -DTARGET=aarch64-apple-darwin ..
            - name: Build
              run: cd build && make -j$(sysctl -n hw.ncpu)
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-aarch64-apple-darwin
                  path: build/

    test-aarch64-apple-darwin:
        runs-on: macos-15
        needs: build-aarch64-apple-darwin
        steps:
            - uses: actions/checkout@v4
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build-aarch64-apple-darwin
                  path: build/
            - name: Restore execute permissions
              run: chmod +x build/bin/*
            - name: Run Tests
              run: cd build && ctest --output-on-failure
