name: aarch64-pc-windows-msvc

on: [push, pull_request]

jobs:
  setup-aarch64-pc-windows-msvc:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

  build-aarch64-pc-windows-msvc:
    runs-on: windows-11-arm
    needs: setup-aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64
      - name: Configure
        run: |
          mkdir build; cd build
          cmake -G "Ninja" -DTARGET=aarch64-pc-windows-msvc -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ..
      - name: Build
        run: cmake --build build --config Release --parallel 4
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-aarch64-pc-windows-msvc
          path: build/

  test-aarch64-pc-windows-msvc:
    runs-on: windows-11-arm
    needs: build-aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-aarch64-pc-windows-msvc
          path: build/
      - name: Run Tests
        run: cd build && ctest --output-on-failure
