name: arm-unknown-linux-gnueabihf
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t fcontext-builder -f docker/Dockerfile .
            - name: Build and Test
              run: |
                  docker run --rm -v ${{ github.workspace }}:/src fcontext-builder \
                    bash -c "mkdir -p build && cd build && \
                    cmake -DTRIPLE=arm-unknown-linux-gnueabihf \
                          -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
                          -DCMAKE_C_FLAGS='-static' \
                          -DCMAKE_SYSTEM_NAME=Linux \
                          -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/qemu-arm \
                          .. && \
                    make && \
                    CTEST_OUTPUT_ON_FAILURE=1 ctest"
