name: armv7-alpine-linux

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.alpine-armv7 .
      - name: Build in Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            bash -c "mkdir -p build && cd build && \
            cmake -DTARGET=arm-unknown-linux-gnueabihf \
                  -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
                  -DCMAKE_SYSTEM_NAME=Linux \
                  .. && \
            cmake --build ."
      - name: Test on Host
        run: |
          cd ${{ github.workspace }}/build && \
          ctest --output-on-failure
