name: i386-unknown-linux-gnu

on: [push, pull_request]

jobs:
  setup-i386-unknown-linux-gnu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-multilib qemu-user

  build-i386-unknown-linux-gnu:
    runs-on: ubuntu-24.04
    needs: setup-i386-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-multilib qemu-user
      - name: Configure and Build
        run: |
          mkdir -p build && cd build
          cmake -DTARGET=i386-unknown-linux-gnu \
                  -DCMAKE_C_COMPILER=gcc \
                  -DCMAKE_C_FLAGS='-m32 -static' \
                  ..
          make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-i386-unknown-linux-gnu
          path: build/

  test-i386-unknown-linux-gnu:
    runs-on: ubuntu-24.04
    needs: build-i386-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-i386-unknown-linux-gnu
          path: build/
      - name: Restore execute permissions
        run: chmod +x build/bin/*
      - name: Run Tests
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 ctest
