name: mips64el-unknown-linux-gnuabi64

on: [push, pull_request]

jobs:
  setup-mips64el-unknown-linux-gnuabi64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.mips64el .

  build-mips64el-unknown-linux-gnuabi64:
    runs-on: ubuntu-24.04
    needs: setup-mips64el-unknown-linux-gnuabi64
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.mips64el .
      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            bash -c "mkdir -p build && cd build && \
            cmake -DTARGET=mips64el-unknown-linux-gnuabi64 \
                  -DCMAKE_C_COMPILER=mips64el-linux-gnuabi64-gcc \
                  -DCMAKE_C_FLAGS='-static' \
                  -DCMAKE_SYSTEM_NAME=Linux \
                  -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/qemu-mips64el \
                  .. && \
            make"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-mips64el-unknown-linux-gnuabi64
          path: build/

  test-mips64el-unknown-linux-gnuabi64:
    runs-on: ubuntu-24.04
    needs: build-mips64el-unknown-linux-gnuabi64
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-mips64el-unknown-linux-gnuabi64
          path: build/
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.mips64el .
      - name: Run Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            bash -c "cd build && CTEST_OUTPUT_ON_FAILURE=1 ctest"
