name: riscv64-alpine-linux

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64
      - name: Build Docker image
        run: docker build -t yafl-builder -f docker/Dockerfile.alpine-riscv64 .
      - name: Build and Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/src yafl-builder \
            bash -c "mkdir -p build && cd build && \
            cmake -DTARGET=riscv64-unknown-linux-gnu \
                  -DCMAKE_C_COMPILER=riscv64-linux-gnu-gcc \
                  -DCMAKE_C_FLAGS='-static' \
                  -DCMAKE_SYSTEM_NAME=Linux \
                  -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/qemu-riscv64 \
                  .. && \
            cmake --build . && \
            ctest --output-on-failure"
